services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandwich_app
    ports:
      - "8080:8080"
    restart: always         #재시작 정책 설정
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      JAVA_TOOL_OPTIONS: "-Duser.timezone=UTC"
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:5432/awesome_sandwich_dev
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SANDWICH_USER_AWS_ACCESS_KEY_ID: ${SANDWICH_USER_AWS_ACCESS_KEY_ID}
      SANDWICH_USER_AWS_SECRET_ACCESS_KEY: ${SANDWICH_USER_AWS_SECRET_ACCESS_KEY}
      PUSH_FCM_ENABLED: "true"
      FIREBASE_CREDENTIALS_PATH: /app/creds/firebase-service-account.json
      APP_WEB_BASE_URL: http://localhost
    volumes:
      - ./firebase-service-account.json:/app/creds/firebase-service-account.json:ro
    networks:
      - sandwich-net

  postgres:
    image: postgres:15
    container_name: sandwich_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: sandwich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c log_min_duration_statement=500
      -c log_statement=none
    networks:
      - sandwich-net

  redis:
    image: redis:7
    container_name: sandwich_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sandwich-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: sandwich_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sandwich.com
      PGADMIN_DEFAULT_PASSWORD: sandwich
    networks:
      - sandwich-net

  nginx:
    image: nginx:1.25
    container_name: sandwich_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../front/build:/app
      - ./public:/app/public   # 사용자 프로젝트 정적파일 저장소 들어갈 곳
    depends_on:
      - app
    environment:
      FIREBASE_VAPID_KEY: ${FIREBASE_VAPID_KEY}
    command: >
      /bin/sh -lc '
      if [ -f /app/public/ws-test.html ]; then
        # ${FIREBASE_VAPID_KEY} 플레이스홀더 → 실제 값으로 치환
        sed -i "s|\\\${FIREBASE_VAPID_KEY}|$FIREBASE_VAPID_KEY|g" /app/public/ws-test.html;
      fi;
      exec nginx -g "daemon off;"
      '
    networks:
      - sandwich-net

volumes:
  pgdata:

networks:
  sandwich-net:
    external: true
