version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recsys
    ports:
      - "5432:5432"
